package inventory

// NameFamily assigns every registered builtin name and CL adapter id to exactly
// one family. It is total over RegisteredNames and CLAdapterIDs: a name missing
// here is a name no seam owns. "support" never appears — it covers helper files,
// which register nothing.
var NameFamily = map[string]string{
	"*":     "numeric",
	"+":     "numeric",
	"-":     "numeric",
	"/":     "numeric",
	"<":     "numeric",
	"<=":    "numeric",
	"=":     "numeric",
	">":     "numeric",
	">=":    "numeric",
	"abs":   "numeric",
	"ceil":  "numeric",
	"floor": "numeric",
	"max":   "numeric",
	"min":   "numeric",
	"mod":   "numeric",
	"neg?":  "numeric",
	"pos?":  "numeric",
	"pow":   "numeric",
	"quot":  "numeric",
	"sqrt":  "numeric",
	"zero?": "numeric",

	"bool?":        "types",
	"float->int":   "types",
	"float?":       "types",
	"fn?":          "types",
	"int->float":   "types",
	"int?":         "types",
	"keyword->str": "types",
	"keyword?":     "types",
	"list?":        "types",
	"macro?":       "types",
	"map?":         "types",
	"nil?":         "types",
	"str->keyword": "types",
	"string?":      "types",
	"symbol?":      "types",
	"type":         "types",
	"vector?":      "types",

	"assoc":     "collection",
	"concat":    "collection",
	"conj":      "collection",
	"cons":      "collection",
	"contains?": "collection",
	"count":     "collection",
	"dissoc":    "collection",
	"empty?":    "collection",
	"first":     "collection",
	"get":       "collection",
	"get-in":    "collection",
	"hash-map":  "collection",
	"keys":      "collection",
	"last":      "collection",
	"list":      "collection",
	"merge":     "collection",
	"nth":       "collection",
	"range":     "collection",
	"rest":      "collection",
	"reverse":   "collection",
	"sort":      "collection",
	"vals":      "collection",
	"vector":    "collection",

	"apply":  "higher-order",
	"assert": "higher-order",
	"filter": "higher-order",
	"map":    "higher-order",
	"reduce": "higher-order",

	"format":              "string",
	"str":                 "string",
	"string->float":       "string",
	"string->int":         "string",
	"string/contains?":    "string",
	"string/ends-with?":   "string",
	"string/join":         "string",
	"string/length":       "string",
	"string/lines":        "string",
	"string/lower":        "string",
	"string/replace":      "string",
	"string/split":        "string",
	"string/starts-with?": "string",
	"string/trim":         "string",
	"string/upper":        "string",

	"cl/mapcar@1": "cl-adapter",
	"cl/nth@1":    "cl-adapter",
	"cl/sort@1":   "cl-adapter",
}
