// Package inventory holds frozen snapshots of the interpreter's registered
// surface. The tables are hand-maintained: a diff against one is the signal
// that a builtin was added, removed, or moved between files.
package inventory

// RegisteredNames maps each stdlib source file to the names it registers as
// Go builtins, sorted. Lisp names defined in bootstrap.go are not part of it.
var RegisteredNames = map[string][]string{
	"plugins/stdlib/arithmetic.go": {
		"*",
		"+",
		"-",
		"/",
		"abs",
		"ceil",
		"floor",
		"max",
		"min",
		"mod",
		"neg?",
		"pos?",
		"pow",
		"quot",
		"sqrt",
		"zero?",
	},
	"plugins/stdlib/comparison.go": {
		"<",
		"<=",
		"=",
		">",
		">=",
	},
	"plugins/stdlib/strings.go": {
		"format",
		"str",
		"string->float",
		"string->int",
		"string/contains?",
		"string/ends-with?",
		"string/join",
		"string/length",
		"string/lines",
		"string/lower",
		"string/replace",
		"string/split",
		"string/starts-with?",
		"string/trim",
		"string/upper",
	},
	"plugins/stdlib/collections.go": {
		"assoc",
		"concat",
		"conj",
		"cons",
		"contains?",
		"count",
		"dissoc",
		"empty?",
		"first",
		"get",
		"get-in",
		"hash-map",
		"keys",
		"last",
		"list",
		"merge",
		"nth",
		"range",
		"rest",
		"reverse",
		"sort",
		"vals",
		"vector",
	},
	"plugins/stdlib/higher_order.go": {
		"apply",
		"filter",
		"map",
		"reduce",
	},
	"plugins/stdlib/control.go": {
		"assert",
	},
	"plugins/stdlib/types.go": {
		"bool?",
		"float->int",
		"float?",
		"fn?",
		"int->float",
		"int?",
		"keyword->str",
		"keyword?",
		"list?",
		"macro?",
		"map?",
		"nil?",
		"str->keyword",
		"string?",
		"symbol?",
		"type",
		"vector?",
	},
}

// CLAdapterIDs are the semantic ids of the CL dialect's adapters, sorted.
var CLAdapterIDs = []string{"cl/mapcar@1", "cl/nth@1", "cl/sort@1"}
